baseurl = "http://edzynda.com/"
languageCode = "en-us"
title = "Ed Zynda - Coder, Hacker, Superhero"
# Define how many pages appear per site
paginate = 5
# Enable comments powered by Disqus by entering your disqus shortname
disqusShortname = "edzynda"

[params]
    site_author = "Ed Zynda"
    site_description = "Coder | Hacker | Superhero"
    location = "Earth"
    # All paths are relative to the baseurl. Put your files
    # somewhere in the static folder.
    avatar = "http://www.gravatar.com/avatar/6f0ca2846bbe006ad4bc12a583387c6a.png?size=200"
    header_background = "img/desk.jpg"
    header_title = "Customizable header title"
    copyright = "© 2016 Ed Zynda."

    # Enable gogle analytics by entering your tracking code
    google_analytics = "UA-56129772-1"

[social]
    # Add your social network accounts to the profile section on the left
    # by entering your username. The links to your account will be
    # create automatically.
    twitter   = "edzynda"
    facebook  = ""
    linkedin  = ""
    behance   = ""
    dribbble  = ""
    instagram = "yungzee83"
    github    = "ezynda3"
    gplus     = ""
